// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	articles "prog/features/articles"

	mock "github.com/stretchr/testify/mock"
)

// Business is an autogenerated mock type for the Business type
type Business struct {
	mock.Mock
}

// CreateArticle provides a mock function with given fields: data
func (_m *Business) CreateArticle(data articles.ArticleCore) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(articles.ArticleCore) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTags provides a mock function with given fields: tags
func (_m *Business) CreateTags(tags []articles.TagCore) ([]articles.TagCore, error) {
	ret := _m.Called(tags)

	var r0 []articles.TagCore
	if rf, ok := ret.Get(0).(func([]articles.TagCore) []articles.TagCore); ok {
		r0 = rf(tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]articles.TagCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]articles.TagCore) error); ok {
		r1 = rf(tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteArticleById provides a mock function with given fields: articleId
func (_m *Business) DeleteArticleById(articleId int) error {
	ret := _m.Called(articleId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(articleId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllArticles provides a mock function with given fields:
func (_m *Business) GetAllArticles() ([]articles.ArticleCore, error) {
	ret := _m.Called()

	var r0 []articles.ArticleCore
	if rf, ok := ret.Get(0).(func() []articles.ArticleCore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]articles.ArticleCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUserArticles provides a mock function with given fields: userId
func (_m *Business) GetAllUserArticles(userId int) ([]articles.ArticleCore, error) {
	ret := _m.Called(userId)

	var r0 []articles.ArticleCore
	if rf, ok := ret.Get(0).(func(int) []articles.ArticleCore); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]articles.ArticleCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetArticleById provides a mock function with given fields: articleId
func (_m *Business) GetArticleById(articleId int) (articles.ArticleCore, error) {
	ret := _m.Called(articleId)

	var r0 articles.ArticleCore
	if rf, ok := ret.Get(0).(func(int) articles.ArticleCore); ok {
		r0 = rf(articleId)
	} else {
		r0 = ret.Get(0).(articles.ArticleCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(articleId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateArticleById provides a mock function with given fields: articleId, data
func (_m *Business) UpdateArticleById(articleId int, data articles.ArticleCore) error {
	ret := _m.Called(articleId, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, articles.ArticleCore) error); ok {
		r0 = rf(articleId, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyArticleOwner provides a mock function with given fields: articleId, userId
func (_m *Business) VerifyArticleOwner(articleId int, userId int) error {
	ret := _m.Called(articleId, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(articleId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
